apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mk-ocr-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itztinq/mk-ocr-platform.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mk-ocr-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
